// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyAcfCETm8SBccecvSS61CmyfFdT6ybCmtM',
    appId: '1:371519671936:web:0b13acdd93c7b032e52065',
    messagingSenderId: '371519671936',
    projectId: 'quicksign-7c212',
    authDomain: 'quicksign-7c212.firebaseapp.com',
    storageBucket: 'quicksign-7c212.firebasestorage.app',
  );

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyAbVkfskwoHVaR90ZU-LqDRFM2y2e6MBOY',
    appId: '1:371519671936:android:cd86b88085bd1d43e52065',
    messagingSenderId: '371519671936',
    projectId: 'quicksign-7c212',
    storageBucket: 'quicksign-7c212.firebasestorage.app',
  );

  static const ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXXQmybJ78ATbzLC-OvvkDrAPeR61uwQ',
    appId: '1:371519671936:ios:b653faecbf8e12c9e52065',
    messagingSenderId: '371519671936',
    projectId: 'quicksign-7c212',
    storageBucket: 'quicksign-7c212.firebasestorage.app',
    iosClientId: '371519671936-13bofoica47keunebe3ftuvpkor2nrb8.apps.googleusercontent.com',
    iosBundleId: 'com.rotem.quicksign',
  );
}
